name: PA
channels:
  - conda-forge
  - defaults
dependencies:
  - langchain
  - pypdf
  # a required package for chromadb, always error when using pip to install it
  - hnswlib
  # for development
  - pytest
  - black
  # pip install
  - pip
  - pip:
    - gradio
    - chromadb
    - openai
    - tiktoken